export const sampleListings = [
  {
    title: 'Tracteur Massey Ferguson 240',
    description: 'Tracteur Massey Ferguson 240 en excellent état, bien entretenu avec toutes les révisions à jour. Moteur puissant et fiable, parfait pour les travaux agricoles de moyenne et grande envergure. Très peu utilisé, comme neuf.',
    price: 95000,
    year: 2018,
    region: 'Rabat-Salé-Kénitra',
    city: 'Kénitra',
    brand: 'Massey Ferguson',
    model: '240',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/2132250/pexels-photo-2132250.jpeg',
      'https://images.pexels.com/photos/2255801/pexels-photo-2255801.jpeg',
    ],
  },
  {
    title: 'Bulldozer Caterpillar D6',
    description: 'Bulldozer Caterpillar D6 robuste et performant. Idéal pour les travaux de terrassement, nivellement et construction. Entretien régulier effectué, pneus neufs, lame en parfait état.',
    price: 250000,
    year: 2017,
    region: 'Marrakech-Safi',
    city: 'Marrakech',
    brand: 'Caterpillar',
    model: 'D6',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/1493146/pexels-photo-1493146.jpeg',
      'https://images.pexels.com/photos/1350370/pexels-photo-1350370.jpeg',
    ],
  },
  {
    title: 'Moissonneuse Claas Dominator',
    description: 'Moissonneuse-batteuse Claas Dominator performante pour grandes cultures. Largeur de coupe 5m, système de battage efficace, cabine climatisée. Prête pour la saison des récoltes.',
    price: 180000,
    year: 2016,
    region: 'Fès-Meknès',
    city: 'Fès',
    brand: 'Claas',
    model: 'Dominator',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/2255801/pexels-photo-2255801.jpeg',
      'https://images.pexels.com/photos/2132250/pexels-photo-2132250.jpeg',
    ],
  },
  {
    title: 'Chargeuse Komatsu WA380',
    description: 'Chargeuse sur pneus Komatsu WA380, capacité de levage 3.5 tonnes. Moteur diesel économique, excellente maniabilité, système hydraulique performant. Utilisée principalement pour chargement de matériaux.',
    price: 220000,
    year: 2019,
    region: 'Casablanca-Settat',
    city: 'Casablanca',
    brand: 'Komatsu',
    model: 'WA380',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/1350370/pexels-photo-1350370.jpeg',
      'https://images.pexels.com/photos/1493146/pexels-photo-1493146.jpeg',
    ],
  },
  {
    title: 'Tracteur New Holland TD5.95',
    description: 'Tracteur New Holland TD5.95, 95 CV, transmission synchronisée 16x16. Hydraulique puissante, cabine confortable avec climatisation. Idéal pour tous types de travaux agricoles.',
    price: 120000,
    year: 2020,
    region: 'Fès-Meknès',
    city: 'Meknès',
    brand: 'New Holland',
    model: 'TD5.95',
    condition: 'new' as const,
    images: [
      'https://images.pexels.com/photos/2132250/pexels-photo-2132250.jpeg',
      'https://images.pexels.com/photos/2255801/pexels-photo-2255801.jpeg',
    ],
  },
  {
    title: 'Pelle hydraulique Hitachi ZX210',
    description: 'Pelle hydraulique Hitachi ZX210 de 21 tonnes, équipée d\'un godet de 1m³. Système hydraulique performant, cabine ergonomique, chenilles en bon état. Parfaite pour excavation et terrassement.',
    price: 310000,
    year: 2018,
    region: 'Tanger-Tétouan-Al Hoceïma',
    city: 'Tanger',
    brand: 'Hitachi',
    model: 'ZX210',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/1350370/pexels-photo-1350370.jpeg',
      'https://images.pexels.com/photos/1493146/pexels-photo-1493146.jpeg',
    ],
  },
  {
    title: 'Niveleuse Volvo G930',
    description: 'Niveleuse automotrice Volvo G930, lame de 3.7m, moteur 6 cylindres diesel. Idéale pour travaux routiers et nivellement de terrains. État impeccable, entretien complet récent.',
    price: 200000,
    year: 2017,
    region: 'Souss-Massa',
    city: 'Agadir',
    brand: 'Volvo',
    model: 'G930',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/1493146/pexels-photo-1493146.jpeg',
      'https://images.pexels.com/photos/1350370/pexels-photo-1350370.jpeg',
    ],
  },
  {
    title: 'Mini-pelle Kubota KX080-4',
    description: 'Mini-pelle Kubota KX080-4, poids opérationnel 8 tonnes, godet 0.28m³. Compact et puissant, parfait pour travaux en espaces restreints. Moteur diesel économique, très maniable.',
    price: 150000,
    year: 2021,
    region: 'Rabat-Salé-Kénitra',
    city: 'Rabat',
    brand: 'Kubota',
    model: 'KX080-4',
    condition: 'new' as const,
    images: [
      'https://images.pexels.com/photos/1350370/pexels-photo-1350370.jpeg',
      'https://images.pexels.com/photos/1493146/pexels-photo-1493146.jpeg',
    ],
  },
  {
    title: 'Tracteur John Deere 5090E',
    description: 'Tracteur John Deere 5090E, 90 CV, transmission 12F/12R. Robuste et fiable, équipé de pneus neufs, hydraulique performante. Excellent pour labour, semis et transport.',
    price: 130000,
    year: 2019,
    region: 'Casablanca-Settat',
    city: 'El Jadida',
    brand: 'John Deere',
    model: '5090E',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/2132250/pexels-photo-2132250.jpeg',
      'https://images.pexels.com/photos/2255801/pexels-photo-2255801.jpeg',
    ],
  },
  {
    title: 'Compacteur Bomag BW120',
    description: 'Compacteur monocylindre Bomag BW120, largeur de travail 1200mm. Système de vibration efficace, moteur diesel économique. Parfait pour compactage de sols et travaux routiers.',
    price: 95000,
    year: 2018,
    region: 'Oriental',
    city: 'Oujda',
    brand: 'Bomag',
    model: 'BW120',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/1493146/pexels-photo-1493146.jpeg',
      'https://images.pexels.com/photos/1350370/pexels-photo-1350370.jpeg',
    ],
  },
  {
    title: 'Tracteur Fendt 724 Vario',
    description: 'Tracteur haut de gamme Fendt 724 Vario, 240 CV, transmission Vario continue. GPS intégré, cabine luxueuse, technologie avancée. Un investissement pour l\'agriculture de précision.',
    price: 450000,
    year: 2020,
    region: 'Casablanca-Settat',
    city: 'Casablanca',
    brand: 'Fendt',
    model: '724 Vario',
    condition: 'new' as const,
    images: [
      'https://images.pexels.com/photos/2132250/pexels-photo-2132250.jpeg',
      'https://images.pexels.com/photos/2255801/pexels-photo-2255801.jpeg',
    ],
  },
  {
    title: 'Rouleau compresseur Dynapac CC1300',
    description: 'Rouleau compresseur tandem Dynapac CC1300, 3 tonnes. Idéal pour compactage d\'asphalte et travaux routiers. Système de vibration double, cabine avec ROPS.',
    price: 175000,
    year: 2017,
    region: 'Marrakech-Safi',
    city: 'Safi',
    brand: 'Dynapac',
    model: 'CC1300',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/1493146/pexels-photo-1493146.jpeg',
      'https://images.pexels.com/photos/1350370/pexels-photo-1350370.jpeg',
    ],
  },
  {
    title: 'Chariot élévateur Toyota 8FD25',
    description: 'Chariot élévateur diesel Toyota 8FD25, capacité 2.5 tonnes, hauteur de levage 4.5m. Fourches ajustables, mât triplex, excellent état mécanique. Idéal pour chantiers et entrepôts.',
    price: 145000,
    year: 2019,
    region: 'Tanger-Tétouan-Al Hoceïma',
    city: 'Tétouan',
    brand: 'Toyota',
    model: '8FD25',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/1350370/pexels-photo-1350370.jpeg',
      'https://images.pexels.com/photos/1493146/pexels-photo-1493146.jpeg',
    ],
  },
  {
    title: 'Bétonnière autoportée Carmix 3.5TT',
    description: 'Bétonnière autoportée Carmix 3.5TT, capacité de malaxage 3.5m³. 4x4 tout-terrain, parfaite pour chantiers difficiles d\'accès. Système de malaxage efficace, moteur diesel robuste.',
    price: 280000,
    year: 2018,
    region: 'Béni Mellal-Khénifra',
    city: 'Béni Mellal',
    brand: 'Carmix',
    model: '3.5TT',
    condition: 'good' as const,
    images: [
      'https://images.pexels.com/photos/1493146/pexels-photo-1493146.jpeg',
      'https://images.pexels.com/photos/1350370/pexels-photo-1350370.jpeg',
    ],
  },
  {
    title: 'Tracteur Case IH Puma 185',
    description: 'Tracteur Case IH Puma 185, 185 CV, transmission CVX continue. Système hydraulique de 140 L/min, relevage 3 points puissant. Configuration premium avec tous les équipements modernes.',
    price: 385000,
    year: 2021,
    region: 'Fès-Meknès',
    city: 'Fès',
    brand: 'Case IH',
    model: 'Puma 185',
    condition: 'new' as const,
    images: [
      'https://images.pexels.com/photos/2132250/pexels-photo-2132250.jpeg',
      'https://images.pexels.com/photos/2255801/pexels-photo-2255801.jpeg',
    ],
  },
];
